# Generated by Django 2.0.6 on 2018-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='codigo',
            field=models.CharField(max_length=250),
        ),
    ]
