# Generated by Django 2.0.6 on 2018-09-24 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_noticia_imagenurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1024)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('nombre_para', models.CharField(max_length=150)),
                ('nombre_con', models.CharField(max_length=150)),
                ('cancelado', models.BooleanField()),
                ('dia_completo', models.BooleanField()),
                ('id_user_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('id_user_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=10)),
                ('dui', models.CharField(max_length=9)),
                ('genero', models.CharField(max_length=9)),
                ('fechas_nac', models.DateField()),
                ('t_fijo', models.CharField(max_length=10)),
                ('t_movil', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('titulo_pre', models.CharField(max_length=30)),
                ('formacion_aca', models.CharField(max_length=30)),
                ('id_user_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id_paso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='pasos',
            name='id_procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Procedimiento'),
        ),
    ]
