# Generated by Django 2.0.6 on 2018-09-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180924_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_con',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_para',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
